import assert from 'node:assert/strict';
import { describe, test } from 'node:test';

import { looksAutoGenerated, parseFileName, resolveNames } from '@/services/file/file-name-parser';

describe('decompor o nome do arquivo', () => {
  test('número de faixa no início, nas grafias comuns', () => {
    for (const nome of ['01 - A.mp3', '01. A.mp3', '01_A.mp3', '1 A.mp3', '007 - A.mp3']) {
      assert.equal(parseFileName(nome).trackNumber !== null, true, nome);
    }
  });

  test('separa título e artista', () => {
    assert.deepEqual(parseFileName('01 - EU IA PARAR - Anderson Porto.mp3'), {
      trackNumber: 1,
      segments: ['EU IA PARAR', 'Anderson Porto'],
    });
  });

  test('aceita travessão além do hífen', () => {
    assert.deepEqual(parseFileName('A – B.mp3').segments, ['A', 'B']);
  });

  test('não parte hífen sem espaço, que costuma ser parte do nome', () => {
    // "Rock-n-Roll" é um título, não três segmentos.
    assert.deepEqual(parseFileName('Rock-n-Roll.mp3').segments, ['Rock-n-Roll']);
  });

  test('nome sem estrutura vira um segmento só', () => {
    assert.deepEqual(parseFileName('Construção.mp3'), {
      trackNumber: null,
      segments: ['Construção'],
    });
  });

  test('não confunde ano com número de faixa', () => {
    // 4 dígitos não são número de faixa.
    assert.equal(parseFileName('1970 - Águas de Março.mp3').trackNumber, null);
  });
});

describe('resolver artista pelo que se repete na pasta', () => {
  test('artista à direita: o caso que motivou isto', () => {
    const nomes = [
      '01 - EU IA PARAR - Anderson Porto.mp3',
      '02 - TRAIDOR - Anderson Porto.mp3',
      '03 - VENCER COM A GALERA - Anderson Porto.mp3',
    ];

    assert.deepEqual(resolveNames(nomes), [
      { title: 'EU IA PARAR', artist: 'Anderson Porto' },
      { title: 'TRAIDOR', artist: 'Anderson Porto' },
      { title: 'VENCER COM A GALERA', artist: 'Anderson Porto' },
    ]);
  });

  test('artista à esquerda: a convenção oposta', () => {
    const nomes = [
      '01 - Chico Buarque - Construção.mp3',
      '02 - Chico Buarque - Cotidiano.mp3',
      '03 - Chico Buarque - Deus lhe pague.mp3',
    ];

    assert.deepEqual(resolveNames(nomes), [
      { title: 'Construção', artist: 'Chico Buarque' },
      { title: 'Cotidiano', artist: 'Chico Buarque' },
      { title: 'Deus lhe pague', artist: 'Chico Buarque' },
    ]);
  });

  test('sem repetição não chuta: devolve artista nulo', () => {
    // Coletânea: cada faixa é de um artista diferente, então nenhum lado
    // repete e não há como saber qual é qual.
    const nomes = ['01 - A - B.mp3', '02 - C - D.mp3'];
    for (const r of resolveNames(nomes)) {
      assert.equal(r.artist, null);
    }
  });

  test('um arquivo sozinho não estabelece padrão', () => {
    assert.deepEqual(resolveNames(['01 - A - B.mp3']), [{ title: 'A', artist: null }]);
  });

  test('nome sem separador vira título inteiro', () => {
    assert.deepEqual(resolveNames(['Construção.mp3']), [{ title: 'Construção', artist: null }]);
  });

  test('três segmentos: o artista sai e o resto vira título', () => {
    const nomes = ['01 - Parte 1 - Parte 2 - Elis.mp3', '02 - Outra - Coisa - Elis.mp3'];
    const r = resolveNames(nomes);
    // Com 3 segmentos não há padrão de 2, então fica em aberto.
    assert.equal(r[0].artist, null);
    assert.equal(r[0].title, 'Parte 1');
  });
});

describe('tag que parece gerada por máquina', () => {
  test('reconhece os padrões que apareceram nos arquivos reais', () => {
    for (const t of ['music 8', 'music 1_2', 'Track 3', 'audio 12', 'faixa 4', 'untitled', '7']) {
      assert.equal(looksAutoGenerated(t, ''), true, t);
    }
  });

  test('título de verdade não é confundido', () => {
    for (const t of ['EU IA PARAR', 'Construção', 'Music of the Spheres', 'Track Star']) {
      assert.equal(looksAutoGenerated(t, ''), false, t);
    }
  });

  test('com artista preenchido, confia na tag', () => {
    // Um ID3v1 completo é uma fonte legítima; só o vazio levanta suspeita.
    assert.equal(looksAutoGenerated('music 8', 'Anderson Porto'), false);
  });

  test('título vazio conta como inutilizável', () => {
    assert.equal(looksAutoGenerated('', ''), true);
    assert.equal(looksAutoGenerated('   ', ''), true);
  });
});

describe('os arquivos reais que motivaram isto', () => {
  /**
   * Álbum baixado solto: sem ID3v2, com ID3v1 preenchido automaticamente
   * (`music 8`, `music 3`, `music 1_2`) e artista vazio. O nome do arquivo era
   * a única fonte real, e a tag de lixo vencia — o usuário via "music 8" no
   * lugar de "EU IA PARAR".
   */
  const arquivos = [
    '01 - EU IA PARAR - Anderson Porto.mp3',
    '02 - TRAIDOR - Anderson Porto.mp3',
    '03 - VENCER COM A GALERA - Anderson Porto.mp3',
    '04 - BUMBUM TANTAN - Anderson Porto.mp3',
    '05 - PRA CASA EU NÃO VOU - Anderson Porto.mp3',
    '06 - ARRUMA A MALA AÊ - Anderson Porto.mp3',
    '07 - VOU INVENTAR DE SER VAQUEIRO - Anderson Porto.mp3',
    '08 - SOCADÃO - Anderson Porto.mp3',
  ];

  const tagsDeLixo = [
    'music 8',
    'music 3',
    'music 1_2',
    'music 4',
    'music 5',
    'music 7',
    'music 2',
    'music 6',
  ];

  test('todas as tags são reconhecidas como inutilizáveis', () => {
    for (const t of tagsDeLixo) {
      assert.equal(looksAutoGenerated(t, ''), true, t);
    }
  });

  test('o álbum inteiro sai com título e artista corretos', () => {
    assert.deepEqual(resolveNames(arquivos), [
      { title: 'EU IA PARAR', artist: 'Anderson Porto' },
      { title: 'TRAIDOR', artist: 'Anderson Porto' },
      { title: 'VENCER COM A GALERA', artist: 'Anderson Porto' },
      { title: 'BUMBUM TANTAN', artist: 'Anderson Porto' },
      { title: 'PRA CASA EU NÃO VOU', artist: 'Anderson Porto' },
      { title: 'ARRUMA A MALA AÊ', artist: 'Anderson Porto' },
      { title: 'VOU INVENTAR DE SER VAQUEIRO', artist: 'Anderson Porto' },
      { title: 'SOCADÃO', artist: 'Anderson Porto' },
    ]);
  });

  test('a numeração da faixa vem junto', () => {
    assert.deepEqual(
      arquivos.map((f) => parseFileName(f).trackNumber),
      [1, 2, 3, 4, 5, 6, 7, 8],
    );
  });
});
