/**
 * Nome de arquivo decomposto.
 *
 * `segments` são os pedaços separados por hífen, já aparados. Um nome como
 * `01 - EU IA PARAR - Anderson Porto.mp3` vira `{ trackNumber: 1, segments:
 * ['EU IA PARAR', 'Anderson Porto'] }`.
 */
export interface ParsedFileName {
  trackNumber: number | null;
  segments: string[];
}

/** Separadores usados na prática entre número, título e artista. */
const SEPARATOR = /\s+[-–—]\s+|\s+_\s+/;

/** Número de faixa no início: `01 - `, `03. `, `07_`, `12 `. */
const LEADING_TRACK = /^(\d{1,3})\s*(?:[-–—_.)\]]\s*|\s+)/;

/**
 * Decompõe o nome do arquivo sem decidir o que é o quê.
 *
 * Separar a decomposição da interpretação é o que permite resolver a
 * ambiguidade depois, olhando a pasta inteira: sozinho, `01 - A - B` não diz se
 * A é o título ou o artista.
 */
export function parseFileName(fileName: string): ParsedFileName {
  const semExtensao = fileName.replace(/\.[^/.]+$/, '');

  const comNumero = LEADING_TRACK.exec(semExtensao);
  const trackNumber = comNumero ? Number(comNumero[1]) : null;
  const resto = comNumero ? semExtensao.slice(comNumero[0].length) : semExtensao;

  const segments = resto
    .split(SEPARATOR)
    .map((s) => s.replace(/[_]+/g, ' ').replace(/\s+/g, ' ').trim())
    .filter(Boolean);

  return { trackNumber, segments };
}

export interface ResolvedName {
  title: string;
  artist: string | null;
}

/**
 * Decide título e artista para um conjunto de arquivos da mesma pasta.
 *
 * Com dois segmentos (`A - B`), qual é o artista depende da convenção de quem
 * organizou: há coleções em `Artista - Título` e coleções em `Título -
 * Artista`. Nenhum arquivo isolado responde isso.
 *
 * A pasta responde: **o artista é o segmento que se repete**. Num álbum, o
 * artista é o mesmo em todas as faixas e o título muda em cada uma. Basta
 * contar. Com um arquivo só, ou com nenhum lado repetindo, a decisão fica em
 * aberto — devolve `artist: null` em vez de chutar, e quem chamou decide se
 * usa a tag ou "Artista Desconhecido".
 */
export function resolveNames(fileNames: string[]): ResolvedName[] {
  const parsed = fileNames.map(parseFileName);

  const doisSegmentos = parsed.filter((p) => p.segments.length === 2);

  // Conta quantas vezes cada valor aparece em cada posição.
  const contar = (indice: number) => {
    const mapa = new Map<string, number>();
    for (const p of doisSegmentos) {
      const chave = p.segments[indice].toLowerCase();
      mapa.set(chave, (mapa.get(chave) ?? 0) + 1);
    }
    return mapa;
  };

  const repeticaoMaxima = (mapa: Map<string, number>) => Math.max(0, ...mapa.values());

  const repeteEsquerda = repeticaoMaxima(contar(0));
  const repeteDireita = repeticaoMaxima(contar(1));

  // Precisa de pelo menos duas faixas concordando para chamar de padrão; com
  // uma repetição só é coincidência tão provável quanto convenção.
  let indiceDoArtista: 0 | 1 | null = null;
  if (doisSegmentos.length >= 2 && repeteEsquerda !== repeteDireita) {
    if (repeteDireita >= 2 && repeteDireita > repeteEsquerda) indiceDoArtista = 1;
    else if (repeteEsquerda >= 2 && repeteEsquerda > repeteDireita) indiceDoArtista = 0;
  }

  return parsed.map(({ segments }) => {
    if (segments.length === 0) return { title: '', artist: null };
    if (segments.length === 1) return { title: segments[0], artist: null };

    if (indiceDoArtista === null) {
      // Sem padrão detectável, o primeiro segmento vira o título — é o que
      // aparece primeiro no nome, e errar o artista é menos grave do que
      // trocar o título por ele.
      return { title: segments[0], artist: null };
    }

    const artista = segments[indiceDoArtista];
    const titulo = segments.filter((_, i) => i !== indiceDoArtista).join(' - ');
    return { title: titulo, artist: artista };
  });
}

/**
 * A tag encontrada merece confiança?
 *
 * ID3v1 tem campos de 30 caracteres fixos e é o que sobra em arquivos passados
 * de mão em mão; costuma vir preenchido automaticamente com lixo. Nos arquivos
 * que motivaram esta função, os títulos eram `music 1`, `music 2`, `music 3` e
 * o artista estava vazio — enquanto o nome do arquivo trazia a informação real.
 *
 * A regra é conservadora: só desconfia quando **não há artista** e o título
 * parece gerado por máquina. Um ID3v1 completo continua tendo preferência sobre
 * o nome do arquivo.
 */
export function looksAutoGenerated(title: string, artist: string): boolean {
  if (artist.trim()) return false;

  const t = title.trim().toLowerCase();
  if (!t) return true;

  return (
    /^(music|audio|track|faixa|untitled|sem\s*t[ií]tulo|unknown)[\s._-]*\d*(_\d+)?$/.test(t) ||
    /^\d+$/.test(t)
  );
}
